CREATE TABLE IF NOT EXISTS items (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	description TEXT,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
);

CREATE INDEX IF NOT EXISTS idx_items_name ON items(name);